config_version = 1
log_level = "info"

[runtime]
poll_interval_ms = 1000

[plugins]
flstudio = true
opencode = true

[outputs]
console = true
discord = true
discord_app_id = 1533559059125637311

[outputs.discord_apps]
"League of Legends" = 1537237947231899678
"FL Studio" = 1537238265537634457