config_version = 1
log_level = "info"

[runtime]
poll_interval_ms = 1000

[plugins]
flstudio = true
antigravity = true
opencode = true

[outputs]
console = true
discord = true
discord_app_id = 1533559059125637311

[outputs.discord_apps]
"FL Studio" = 1537238265537634457
"OpenCode" = 1538988824623972492
"Antigravity" = 1440730997460172810