config_version = 1
log_level = "info"

[runtime]
poll_interval_ms = 1000

[plugins]
flstudio = true
antigravity = true
opencode = true

[outputs]
console = true
discord = true
discord_app_id = 1533559059125637311

[outputs.discord_apps]
"FL Studio" = 1192880494086455357
Antigravity = 1543009205785591868
OpenCode = 1273940066603106328

[presence]
ownership = "Foreground"
unsupported_foreground = "KeepLast"
